### ISSUE TITLE
Update sharelatex version:  3.2.0

### ISSUE THREAD

**Issue by jjc-sri** [siaimes/sharelatex#1]
> If [version](https://github.com/overleaf/toolkit/blob/master/lib/config-seed/version#L1) of sharelatex updated, please let me know.

The sharelatex version has been updated to 3.2.0

https://github.com/overleaf/toolkit/blob/master/lib/config-seed/version#L1

> 3.2.0

**Comment by jjc-sri** [comment]
Hi,

Thanks for updating the repo so quickly.

Do you know what caused the github actions pipeline to fail to push to dockerhub for v3.2.0?

**Comment by siaimes** [comment]
I haven't located the issue yet.

**Comment by siaimes** [comment]
3.2.2 Hotfix compilation succeeded.

**Comment by siaimes** [comment]
@jjc-sri 3.3.0 complilation succeeded, have a try.
